apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Minicash
  description: The backstage sub-department
spec:
  type: sub-department
  profile:
    displayName: Minicash
    email: backstage@example.com
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: btech-corp
  children: [team-a, team-b, team-c, team-d]
