apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Customer-Journey
  description: Squad MC 
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-mc@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: minicash
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: tatiana.k
spec:
  profile:
    # Intentional no displayName for testing
    email: tatiana-k@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jon.dowey
spec:
  profile:
    displayName: Jon Dowey
    email: jon-dowey@example.com
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [team-mc]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: elon.m
spec:
  profile:
    displayName: Elon M
    email: elon-m@example.com
    picture: https://avatars.dicebear.com/api/avataaars/nigel-manning@example.com.svg?background=%23fff
  memberOf: [team-mc]
---
# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [team-mc]
