apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend: Web application of MiniCash 2.0
  # This is an extra long description
  description: The Petstore is an example API used to show features of the OpenAPI spec.
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
