apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  # This is an extra long description
  description: Web application of MiniCash 2.0
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: squad-mc
  providesApis:
    - petstore
    - streetlights
    - hello-world
