apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wallet: e-Wallet service
  description: Artist main website
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: artist-engagement-portal
  consumesApis: ['component:artist-lookup']
